[workspace]
members = [".", "tests/postgres", "tests/mysql", "tests/sqlite", "tests/mixed"]
default-members = ["."]
resolver = "2"

[package]
name = "diesel-fastrace"
version = "0.1.2"
edition = "2024"
description = "fastrace tracing for Diesel queries"
license = "MPL-2.0"
repository = "https://github.com/codyps/diesel-fastrace"
readme = "README.md"
exclude = ["tests"]
keywords = ["diesel", "fastrace", "postgres", "tracing"]
categories = ["database", "development-tools::debugging"]

[dependencies]
diesel = { version = "2.3.0", default-features = false }
fastrace = { version = "0.7.19", features = ["enable"] }
url = "2.5.4"

[dev-dependencies]
diesel = { version = "2.3.0", default-features = false, features = ["postgres_backend", "i-implement-a-third-party-backend-and-opt-into-breaking-changes"] }
